### ISSUE TITLE
cacert code issue - after using cacert code given in this repo and deploying to openshift. I'm seeing error - java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty 

### ISSUE THREAD

**Issue by dixitneha** [cloudfirst-dev/openshift-ca-trusts#7]
Following error after adding configmap for cacert and mount path as given in the code java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

**Comment by mathianasj** [comment]
I will take a look and let you know what I find

**Comment by dixitneha** [comment]
Thanks! Also, I couldn't add mount path as mountPath: /etc/pki/ca-trust/extracted/java/cacerts 
it was giving error that cacerts is not a directory so then i added only till mountPath: /etc/pki/ca-trust/extracted/java/
not sure if this has anything to do the error i'm getting currently.

**Comment by dixitneha** [comment]
there was an issue with configMap's case in my code ...I was using following which was giving the error i posted earlier
volumes:
            - name: ca-trust
              configmap:
                name: ca-trust
                defaultMode: 420
But after changing  to following it worked fine
volumes:
            - name: ca-trust
              configMap:
                name: ca-trust
                defaultMode: 420

Code is all good. thanks for sharing!
